[package]
name = "v0-7-showcase"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["console", "Window", "Document", "Element", "HtmlElement"] }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib_debug.rs"
